name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rust:
    container:
      image: docker.pkg.github.com/10xdev/toolchain-scripts/toolchain:latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Run Rust tests
        run: cargo build --release
      - name: Check toolchain
        run: readelf -V target/release/vartrix
