name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rust:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u 10xbuild -p ${{secrets.GITHUB_TOKEN}}
      - name: Run Rust tests
        run: >
          docker run -v ${{github.workspace}}:/root
          docker.pkg.github.com/10xdev/toolchain-scripts/toolchain:latest
          /bin/bash -lec '
          cargo build --release;
          target/release/vartrix --help;
          readelf -V target/release/vartrix;
          '
