name: Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u 10xbuild -p ${{secrets.GH_PAT}}
      - name: Run Rust tests
        run: >
          docker run -v ${{github.workspace}}:/root
          docker.pkg.github.com/10xdev/toolchain-scripts/toolchain:latest
          /bin/bash -lec '
          apt-get update && apt-get install -y --no-install-recommends ca-certificates;
          cargo build --release;
          target/release/vartrix --help | grep -q USAGE;
          readelf -V target/release/vartrix;
          ';
          mkdir ${{runner.temp}}/artifacts;
          cp -a target/release/vartrix ${{runner.temp}}/artifacts/vartrix-linux
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: vartrix
          path: ${{runner.temp}}/artifacts
  macos:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Run Rust tests
        run: |
          cargo build --release
          target/release/vartrix --help | grep -q USAGE
          mkdir ${{runner.temp}}/artifacts
          cp -a target/release/vartrix ${{runner.temp}}/artifacts/vartrix-macos
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: vartrix
          path: ${{runner.temp}}/artifacts
